name: nofake

on:
  workflow_dispatch:
    inputs:
      haxball_room_url:
        description: 'Link de la sala de Haxball'
        required: true
        default: 'https://www.haxball.com/play?c=QuvLuoyYbK8'
      mensaje:
        description: 'Mensaje para el raid'
        required: true
        default: 'Raid por Stefano365p'
      llamar_admin:
        description: 'Mensaje para llamar al administrador'
        required: true
        default: 'sexo'

jobs:
  run-bots:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 27
      matrix:
       job_id: [momo, momoelmomo, momito, momolord, momax, momitron, momogod, momacho, momotrix, momus, momotaku, momorito, momochan, momotix, momokun, momillo, momolín, momoloco, momoxD, momelon, momobro, momaster, momoko, momochi, momazo, momardo, momardo69, momardoXD, momoncio, momochulo, momaximo, momex, momaru, momavicho, momomeme, momardo777, momogordo, momitroll, momolf, momix, lulux, luluco, lulu, luludu, lulomomo, lulumax, lulotron, lulex, lulozo, luluzito, bobo, bobito, boboncio, bobox, bobardo, bobardo69, bobardoXD, boboloco, bobitoXD, bobogod, bobazo, bobín, bobochan, bobobro, bobotrix, bobotaku, bobillo, boboxD, bobardo777, bobatron, virgomax, elvirgo, virgenin, virgodios, virgoking, virgotron, supervirgo, virgolandia, virgulín, virguito, virgyxd, virgodemon, virginator, elvirgencio, virgoloco, virgomomazo, virgobro, virgo777, virgoman, virgox, chuchu, chuchin, chuchardo, chuchazo, chuchoxD, chuchotron, chuchoman, chuchinito, chuchuki, chuchuki69, chuchomeme, chuchardoXD, chuchusito, chuchux, chuchofly, chuchucho, chuchardo777, chuchop, chuchobro, chuchoncio, kekin, kekardo, kekomax, kekotron, kekoxD, kekinito, kekardo69, kekop, kekoloco, kekobro, pepo, pepardo, pepin, pepotron, pepazo, pepochan, pepux, pepoxD, pepito69, pepardoXD, pepotronico, pepinito, pepomeme, pepogod, pepobro, peporro, pepochulo, pepelol, pepox, pepix, titin, titardo, titazo, titotron, titomax, titobro, titux, tituxD, titillo, titotronico, cucu, cucurucho, cucuxD, cucardo, cucotron, cucobro, cucomax, cucop, cucomeme, cucinito, lolin, lolardo, lolazo, lolotron, lolobro, lolicoxD, lolojaja, lolito69, lolmax, lolpito, memin, memardo, memotron, memazo, memodios, memobro, memoxD, memopito, memochan, memardoXD, memolandia, memobicho, memotrix, meminito, memogod, meminchu, memotronico, memop, memardón, memotaku, kikin, kikardo, kikotron, kikobro, kikomax, kikoxD, kikoncio, kikofly, kikolandia, kikillo, tunin, tunardo, tunazo, tunobro, tunomax, tunoxD, tunotronico, tunop, tunardón, tunoro, lolinchu, bubilin, cacardo, popoxD, rolo, rolotron, rolotaku, rolobro, rolax, rolito]

    env:
      HAXBALL_ROOM_URL: ${{ github.event.inputs.haxball_room_url }}
      MENSAJE: ${{ github.event.inputs.mensaje }}
      LLAMAR_ADMIN: ${{ github.event.inputs.llamar_admin }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias limpias (incluye puppeteer completo)
        run: |
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
          npm ci

      - name: Esperar inicio sincronizado
        run: sleep $((RANDOM % 10 + 5))

      - name: Ejecutar bot
        run: node botsstefano.js
        env:
          JOB_ID: ${{ matrix.job_id }}
        timeout-minutes: 60
