name: nofake

on:
  workflow_dispatch:
    inputs:
      haxball_room_url:
        description: 'Link de la sala de Haxball'
        required: true
        default: 'https://www.haxball.com/play?c=QuvLuoyYbK8'
      mensaje:
        description: 'Mensaje para el raid'
        required: true
        default: 'Raid por Stefano365p'
      llamar_admin:
        description: 'Mensaje para llamar al administrador'
        required: true
        default: 'sexo'

jobs:
  run-bots:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 27
      matrix:
       job_id: [Cavani, Paredes, Álvarez, Rodríguez, Borré, Zuculini, Romero, Figal, Sosa, Miranda, González, Cortéz, Barco, Martínez, Fernández, Romero, Cabrera, Andrada, Díaz, Campaña, González, Bértoli, Lópes, Carranza, Rodríguez, Rodríguez, Álvarez, Palacios, Zaracho, Payero, Peruzzi, Medina, Orozco, Domínguez, Berterame, Casco, Dátolo, Pratto, Pereyra, Castro, Enzo, Rodríguez, Navarro, Aguirre, Acevedo, Martínez, Tapia, Castro, Rojas, López, Moralez, Berón, González, Blasi, Sosa, Castrillón, Molinas, Chávez, Ferrari, Cabrera, Ferreyra, Fernández, Bocchino, Marcone, Poblete, Lanaro, Sánchez, Nervo, Toloza, Yacob, Cángele, Calderón, Martínez, González, Gutiérrez, Martínez, Pulga, Silva, Garro, Barros, Medina, Herrera, Benegas, Herrera, Piovi, Molina, Salazar, Escobar, Alustiza, Chávez, García, Rodríguez, Pereyra, Martínez, Castro, Fértoli, Pereyra, Castellano, Cauteruccio, Velázquez, Leiva, Recalde, Moreno, Buonanotte, Zárate, Aguirre, Mena, Cuello, Cardona, Álvarez, Moreno, Yacob, González, Múñoz, Álvarez, Gutiérrez, Berón, Pizzini, Sosa, Romero, Ríos, Sosa, Díaz, Neri, González, López, Melli, Pando, Morales, Salinas, Carranza, Cordero, Oviedo, Díaz, López, Rodríguez, Vélez, Ferreyra, Vera, De León, Rodríguez, González, Lema, Melano, Recalde, Vera, Ledesma, Salvio, Muñoz, Blanco, Cordero, Rodríguez, Santos, Gómez, López, Múñoz, Romero, García, Salto, Rodríguez, Solís, Romero, Díaz, Vega, Martínez, Correa, Sánz, Sosa, Demaio, Rojas, Lucas, Blanco, Varela, García, Cordero, Gómez, Cagna, Ríos, Mena, García, González, Rodríguez, Martínez, Mazzola, González, Casco, López, Vázquez, Fariña, Sánchez, Marín, Núñez, Rodríguez, Domínguez, García, Romero, Jara, Espinoza, Tello, Mena, Maza, Montiel, Díaz, Rodríguez, Navarro, Romero, Suárez, De La Cruz, Ríos, Gutiérrez]

    env:
      HAXBALL_ROOM_URL: ${{ github.event.inputs.haxball_room_url }}
      MENSAJE: ${{ github.event.inputs.mensaje }}
      LLAMAR_ADMIN: ${{ github.event.inputs.llamar_admin }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias limpias (incluye puppeteer completo)
        run: |
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
          npm ci

      - name: Esperar inicio sincronizado
        run: sleep $((RANDOM % 10 + 5))

      - name: Ejecutar bot
        run: node botsstefano.js
        env:
          JOB_ID: ${{ matrix.job_id }}
        timeout-minutes: 60
