name: nofake

on:
  workflow_dispatch:
    inputs:
      haxball_room_url:
        description: 'Link de la sala de Haxball'
        required: true
        default: 'https://www.haxball.com/play?c=wL71co1STPI'
      mensaje:
        description: 'Mensaje para el raid'
        required: true
        default: 'Raid por Teleese - 10k for this shitcode? Lol no worth '
      llamar_admin:
        description: 'Mensaje para llamar al administrador'
        required: true
        default: 'sexo'

jobs:
  run-bots:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 27
      matrix:
        job_id: ["COM | Juanito", "COM | Pablito", "COM | Carmelo", "COM | Dario", "COM | Lucas", "COM | Santi", "COM | Charly", "COM | Martin", "COM | Andres", "COM | Franco", "COM | Rolo", "COM | Tobi", "COM | Elian", "COM | Maxi", "COM | Brian", "COM | Cata", "COM | Nacho", "COM | Gaston", "COM | Zorro", "COM | Guille", "COM | Lucho", "COM | Fede", "COM | Matias", "COM | Tato", "COM | Leo", "COM | Agus", "COM | Marcelo", "COM | Domi", "COM | Romi", "COM | Nico", "COM | Tomi", "COM | Sergio", "COM | Juli", "COM | Ricardo", "COM | Pablo", "COM | Guido", "COM | Emiliano", "COM | Chano", "COM | Juani", "COM | Mariano", "COM | Ariel", "COM | Javi", "COM | Lautaro", "COM | Gabo", "COM | Facu", "COM | Vicky", "COM | Diego", "COM | Alan", "COM | Abel", "COM | Chavo", "COM | Roque", "COM | Gonzalo", "COM | Nando", "COM | Leandro", "COM | Rami", "COM | Andy", "COM | Miguel", "COM | Rosi", "COM | Niki", "COM | Fabian", "COM | Alberto", "COM | Luis", "COM | Darian", "COM | Benja", "COM | Tano", "COM | Juan", "COM | Titi", "COM | Nano", "COM | Dami", "COM | Guada", "COM | Oti", "COM | Gonza", "COM | Omar", "COM | Jere", "COM | Dani", "COM | Uli", "COM | Esteban", "COM | Marco", "COM | Bauti", "COM | Manuel", "COM | Tomas", "COM | Emi", "COM | Eze", "COM | Damian", "COM | Hernan", "COM | Ruli", "COM | Gustavo", "COM | Ezequiel", "COM | Guillermo", "COM | Patricio", "COM | Julian", "COM | Augusto", "COM | Mario", "COM | Rodrigo", "COM | Cristian", "COM | Kevin", "COM | Bruno", "COM | Mateo", "COM | Thiago", "COM | Santiago", "COM | Ramiro", "COM | Agustin", "COM | Jonatan", "COM | Mariano", "COM | Esteban", "COM | Blas", "COM | Axel", "COM | Fermin", "COM | Lauti", "COM | Joel", "COM | Federico", "COM | Alex", "COM | Ian", "COM | Brian", "COM | Matheo", "COM | Hugo", "COM | Isaac", "COM | Tomas", "COM | Franco", "COM | Manuel", "COM | Pedro", "COM | Gonzalo", "COM | Pablo", "COM | Ivan", "COM | Omar", "COM | Elías", "COM | Simon", "COM | Nahuel", "COM | Enzo", "COM | Dante", "COM | Jeremias", "COM | Luciano", "COM | Joaquín", "COM | Mauro", "COM | Braian", "COM | Valentino", "COM | Ariel", "COM | Ismael", "COM | Diego", "COM | Ramiro", "COM | Bruno", "COM | Nico", "COM | Julian", "COM | Andres", "COM | Elian", "COM | Marcelo", "COM | Ruben", "COM | Benjamin", "COM | Leo", "COM | Lautaro", "COM | Thiago", "COM | Alan", "COM | Fabio", "COM | Jonathan", "COM | Jorge", "COM | Matias", "COM | Tobias", "COM | Lucas", "COM | Santi", "COM | Nacho", "COM | Fede", "COM | Guille", "COM | Lucho", "COM | Charly", "COM | Gabo", "COM | Facu", "COM | Maxi", "COM | Tato", "COM | Juani", "COM | Martin", "COM | Nico", "COM | Tobi", "COM | Leo", "COM | Agus", "COM | Lauti", "COM | Sergio", "COM | Emiliano", "COM | Javi", "COM | Esteban", "COM | Julian", "COM | Gonzalo", "COM | Ariel", "COM | Dani", "COM | Elian", "COM | Andy", "COM | Marcelo", "COM | Damian", "COM | Pablo", "COM | Luis", "COM | Mariano", "COM | Ricky", "COM | Zorro", "COM | Brian", "COM | Franco", "COM | Matias", "COM | Lucas", "COM | Kevin", "COM | Chano", "COM | Tato", "COM | Fede", "COM | Martin", "COM | Leo", "COM | Juan", "COM | Tomas", "COM | Alex", "COM | Ivan", "COM | Nico"]

    env:
      HAXBALL_ROOM_URL: ${{ github.event.inputs.haxball_room_url }}
      MENSAJE: ${{ github.event.inputs.mensaje }}
      LLAMAR_ADMIN: ${{ github.event.inputs.llamar_admin }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias limpias (incluye puppeteer completo)
        run: |
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
          npm ci

      - name: Ejecutar bot
        run: node botsstefano.js
        env:
          JOB_ID: ${{ matrix.job_id }}
        timeout-minutes: 60

