name: nofake

on:
  workflow_dispatch:
    inputs:
      haxball_room_url:
        description: 'Link de la sala de Haxball'
        required: true
        default: 'https://www.haxball.com/play?c=QuvLuoyYbK8'
      mensaje:
        description: 'Mensaje para el raid'
        required: true
        default: 'Raid por Stefano365p'
      llamar_admin:
        description: 'Mensaje para llamar al administrador'
        required: true
        default: 'sexo'

jobs:
  run-bots:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 27
      matrix:
       job_id: [pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi, pipi]

    env:
      HAXBALL_ROOM_URL: ${{ github.event.inputs.haxball_room_url }}
      MENSAJE: ${{ github.event.inputs.mensaje }}
      LLAMAR_ADMIN: ${{ github.event.inputs.llamar_admin }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias limpias (incluye puppeteer completo)
        run: |
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
          npm ci

      - name: Esperar inicio sincronizado
        run: sleep $((RANDOM % 10 + 5))

      - name: Ejecutar bot
        run: node botsstefano.js
        env:
          JOB_ID: ${{ matrix.job_id }}
        timeout-minutes: 60
