name: Run Node.js Script with Multiple Jobs

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      max_parallel:
        description: 'Maximum parallel jobs'
        required: false
        default: '11'
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 11
      matrix:
        job_id: [
        "thr1.AAAAAGiRbcB5xfithUjWjg.V7EAZ8EXgX0",
"thr1.AAAAAGiRbhCtSmaZONq96Q.ESwkahzZ_5M",
"thr1.AAAAAGiRbiJ3chOnOqI92A.jLFf6_yp3Gk",
"thr1.AAAAAGiRbjsu6JP0hFRYmg._CFvway7TJg",
 "thr1.AAAAAGiRbmUZRy4B3yb2BQ.fH8tkDj-pDI",
"thr1.AAAAAGiRbrLSiVczyU5rYg.StrtLazvMME",
"thr1.AAAAAGiRbrq0y3kt9-4ExA.PgnwPOLZSFE",
 "thr1.AAAAAGiRbsFGJyTRjVZWdA.8DUpO53e9zE",
 "thr1.AAAAAGiRbsjK-aZGjzZO8w.gykUkSJeA0I",
"thr1.AAAAAGiRbuDGZ7oFr5EGaQ.NcvAfSicviI"

        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias (incluye haxball.js)
        run: |
          npm install haxball.js
          npm install  # Esto instalará también tus otras dependencias del package.json si existen

      - name: Esperar inicio sincronizado
        run: sleep $((RANDOM % 10 + 5))

      - name: Ejecutar script
        run: node host.js
        env:
          JOB_ID: ${{ matrix.job_id }}
