name: Run Node.js Script with Multiple Jobs

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      max_parallel:
        description: 'Maximum parallel jobs'
        required: false
        default: '11'
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 11
      matrix:
        job_id: [
"thr1.AAAAAGjlaMxzHFfRnF74IQ.tCmivRMNYPM",
"thr1.AAAAAGjlaNytz7ApAVf9RQ.6qtcO3Kr6to",
"thr1.AAAAAGjlaOje7i__4UBxog.oINbBENtzEw",
"thr1.AAAAAGjlaPP1jBiGoiQ5Ag.NkYLX2yHWzY",
"thr1.AAAAAGjlaP4LyDGXNHxOlg.kj32BhkKxfk",
"thr1.AAAAAGjlaQoLcAtyB_sIcw.eeM8FegGyQA",
"thr1.AAAAAGjlaRmIBj1Qy6iggg.1TcnAEhh-Vw",
"thr1.AAAAAGjlaSQ-eiQIuQsEqQ.gcJMH7uwbYs",
"thr1.AAAAAGjlaUzGFDGYmhyNXQ.jDQ_wrgN97k",
"thr1.AAAAAGjlaVnb0fCcJDCC7g.rHY_kFr5dns",
"thr1.AAAAAGjlaWgy7hKKM4P77g.rMyNk7-9OyY"
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias (incluye haxball.js)
        run: |
          npm install haxball.js
          npm install  # Esto instalará también tus otras dependencias del package.json si existen

      - name: Esperar inicio sincronizado
        run: sleep $((RANDOM % 10 + 5))

      - name: Ejecutar script
        run: node hostbots.js
        env:
          JOB_ID: ${{ matrix.job_id }}
