name: Host - Recaptcha Rooms

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: haxball-recaptcha-hosts
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 11
      matrix:
        include:
          - recaptcha_token: "thr1.AAAAAGlSoyx-rPAE_-wEjA.vrwALknjua4"
            index: 0
          - recaptcha_token: "thr1.AAAAAGlSozpVSyWY5hPFVw.LZ2mUgaRWKo"
            index: 1
          - recaptcha_token: "thr1.AAAAAGlSo0OqYPcnwH9DxA.tFfq62FMWnY"
            index: 2
          - recaptcha_token: "thr1.AAAAAGlSo03I2qiXt9tLOg.PzDVRdnYLz0"
            index: 3
          - recaptcha_token: "thr1.AAAAAGlSo1uVemC5mhFazA.y9Y8M6F7Y-g"
            index: 4
          - recaptcha_token: "thr1.AAAAAGlSo2WOzd5BaF8i8w.UUdVo4XqPx0"
            index: 5
          - recaptcha_token: "thr1.AAAAAGlSo25T1o-7vsg3Hw.Iymy-pu9kUU"
            index: 6
          - recaptcha_token: "thr1.AAAAAGlSo4KBzp7QvOZsEQ.JzgeXx-w5Gg"
            index: 7
          - recaptcha_token: "thr1.AAAAAGlSo61ZMpQywvmPiA.7wSO6dMBibs"
            index: 8
          - recaptcha_token: "thr1.AAAAAGlSo9T0xHlXsjBl9A.SbBtuo5HnXE"
            index: 9
          - recaptcha_token: "thr1.AAAAAGlSo_rukkZUkADOdg.ZLuPgvbGgkE"
            index: 10

    steps:
      - name: 🧩 Checkout repo
        uses: actions/checkout@v4

      - name: 🧹 Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🚀 Ejecutar host
        run: node hosts.js
        env:
          INDEX: ${{ matrix.index }}
          RECAPTCHA_TOKEN: ${{ matrix.recaptcha_token }}
          ROOM_PASSWORD: ""
          PLAYER_NAME: "Teleese"
          PLAYER_AVATAR: "👽"
