name: Run Node.js Script with Multiple Jobs

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      max_parallel:
        description: 'Maximum parallel jobs'
        required: false
        default: '11'
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 11
      matrix:
        job_id: [
      "thr1.AAAAAGjjUQi1QF3_rqeulg.cGQWzUn1gHM",
"thr1.AAAAAGjjTEoIK2QuTRnAWQ.DX9D4a9srZU",
"thr1.AAAAAGjjTMOW6uALza-Gaw.9XU5wpY7gu4",
"thr1.AAAAAGjjTTMb6V5neC0o7w.QxvVOGC2Ox0",
"thr1.AAAAAGjjUGTzJfLAqhfPgA.SPFpN3q0CE4",
"thr1.AAAAAGjjUNOid0ON-5xgyg.zEl7kIWWAeQ",
"thr1.AAAAAGjjUWemSY4ePjSqGA.rroce70LiDA",
"thr1.AAAAAGjjUfCRAKyvWF4IAw.zAwMo9C5yMQ",
"thr1.AAAAAGjjUfzVJBEr3S0qLQ.YWb_UVsjUk8",
"thr1.AAAAAGjjUgUix-ZsL9RgDA.he1CYgyEHp4",
"thr1.AAAAAGjjUhCG0uXBqIw6Xg.W-VWCIBmbE4",
"thr1.AAAAAGjjUhuQtafZgaIn4g.Cutbxff2Mjk",
"thr1.AAAAAGjjUiY6fdpcA7k77w.VfXO3Koymyw",
"thr1.AAAAAGjjUjCf1D8cGJWu5w.B1NHwKlgyJA"
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias (incluye haxball.js)
        run: |
          npm install haxball.js
          npm install  # Esto instalará también tus otras dependencias del package.json si existen

      - name: Esperar inicio sincronizado
        run: sleep $((RANDOM % 10 + 5))

      - name: Ejecutar script
        run: node hostbots.js
        env:
          JOB_ID: ${{ matrix.job_id }}
