name: Run Node.js Script with Multiple Jobs

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      max_parallel:
        description: 'Maximum parallel jobs'
        required: false
        default: '11'
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 11
      matrix:
        job_id: [
  "thr1.AAAAAGjj9FcosBRP8AQ6cw.GyFCYDMcBes",
"thr1.AAAAAGjj9G4JSQXfBuN3UQ.z92wPWyLvSc",
"thr1.AAAAAGjj9HullibLq-XBRw.-l4M07tR1vA",
"thr1.AAAAAGjj9I3S65ANT-y4KQ.u2MQ7sgIpy8",
"thr1.AAAAAGjj9J5fwJJa7WfQrQ.K_kfS985qMQ",
"thr1.AAAAAGjj9K02RK_oTfHBuQ.phPVGRVk-tY",
"thr1.AAAAAGjj9Lgf-we0UANWcQ.XL2Z2PDMnOc",
"thr1.AAAAAGjj9Ma04da7Rijd_Q.xPfdhdhNfrs",
"thr1.AAAAAGjj9NXon33eM7S0GA.8JNnzjm71PM",
"thr1.AAAAAGjj9OLaMNoftWXGdg.-pTxnRLDowE",
"thr1.AAAAAGjj9O_uVExrDxW21A.mcTGyMucxh0"
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias (incluye haxball.js)
        run: |
          npm install haxball.js
          npm install  # Esto instalará también tus otras dependencias del package.json si existen

      - name: Esperar inicio sincronizado
        run: sleep $((RANDOM % 10 + 5))

      - name: Ejecutar script
        run: node hostbots.js
        env:
          JOB_ID: ${{ matrix.job_id }}
